### ISSUE TITLE
Login doesn't work

### ISSUE THREAD

**Issue by vinch** [icure/icure-ehr-lite-react-js-boilerplate-app-template#3]
I was able to create an account but when trying log in, after entering the validation code and submitting the form, I got a 401 error from https://krakenc.icure.cloud/rest/v1/auth/login?ts=1691496840452 :(

Any idea what it could be?

**Comment by vinch** [comment]
Thanks for the answer!

Unfortunately, I get the same error with krakenc.icure.cloud :(

![Screenshot 2023-08-09 at 08 52 09](https://github.com/icure/icure-ehr-lite-react-js-boilerplate-app-template/assets/155370/1f3414f0-d731-4c7e-a07c-29c854aafc3b)

**Comment by vinch** [comment]
Note that I see the patient in the database with plenty of authentication tokens.

![Screenshot 2023-08-09 at 08 53 33](https://github.com/icure/icure-ehr-lite-react-js-boilerplate-app-template/assets/155370/9867f631-b0c6-41c2-8e63-23b26198057b)

**Comment by LotuxPunk** [comment]
Thanks, we're investigating, we come back to you asap

**Comment by LotuxPunk** [comment]
We're unable to replicate the issue using the boiler template on our side

Could you confirm that you have the latest version of `@icure/ehr-lite-sdk` which is `1.0.0` ?

Also, did you do any change on the `auth.api.ts` file ?

**Comment by LotuxPunk** [comment]
Could you also provide us (from the `yarn.lock`) the version of the `@icure/api` ?

**Comment by vinch** [comment]
Thank you Clément.

**Comment by LotuxPunk** [comment]
Hey @vinch 👋 

We are still investigating an issue that could be causing the behavior you are experiencing. We will keep you updated on the progress soon!

**Comment by trema96** [comment]
Hi @vinch,

we have just released an update to our backend which should solve the login issue. There is also a small update to the EHR Lite SDK (`1.0.1`), but it should be unrelated from this issue.

**Comment by vinch** [comment]
Thank you @trema96, I will have a look at that ASAP.

**Comment by vinch** [comment]
The login works now!

Just one last thing: after login, I don't see the text because it's white on white.

![Screenshot 2023-08-11 at 13 55 38](https://github.com/icure/icure-ehr-lite-react-js-boilerplate-app-template/assets/155370/ce9b7466-22de-4077-bd7c-336f5e29f796)

![Screenshot 2023-08-11 at 13 55 43](https://github.com/icure/icure-ehr-lite-react-js-boilerplate-app-template/assets/155370/3022174a-15cc-43fb-acc7-e482b9ac4a96)

**Comment by LotuxPunk** [comment]
Fantastic! Don't hesitate to get back to us if you have any questions or problems!

Ah indeed, we'll fix the template ASAP 😬
